import { Player, Event, Task, DemoUser, FeatureFlags } from '@/types';

export const DEFAULT_FLAGS: FeatureFlags = {
  daily_brief: true,
  portal_live: true,
  players_module: true,
  player_profile: true,
  tasks_module: true,
  program_dna: true,
  audit_logging: true,
  compliance_guardrails: true,
  coach_agent: false,
  memory_engine: false,
  alerts_realtime: false,
  sms_daily: false,
  coach_network_pro: false,
  enterprise_institutional: false,
  api_licensing: false,
  film_ai: false,
  nil_engine: false,
};

export const DEMO_USERS: DemoUser[] = [
  { id: 'u1', name: 'Coach Williams', role: 'HC' },
  { id: 'u2', name: 'Marcus Johnson', role: 'GM' },
  { id: 'u3', name: 'Sarah Chen', role: 'Assistant' },
  { id: 'u4', name: 'Tyler Brooks', role: 'Analyst' },
  { id: 'u5', name: 'Jennifer Martinez', role: 'Compliance' },
];

export const SEED_PLAYERS: Player[] = [
  {
    id: 'p1',
    name: 'Jaylen Carter',
    position: 'QB',
    positionGroup: 'Offense',
    size: '6\'3" 215 lbs',
    eligibility: 'RS Junior',
    origin: 'Ohio State',
    pool: 'Transfer',
    fitScore: 94,
    readinessScore: 88,
    riskScore: 12,
    reasons: ['Elite arm talent', 'Pro-style system experience', 'Leadership qualities', 'High football IQ'],
    flags: ['NIL expectations may be high'],
    filmLinks: ['https://example.com/film1', 'https://example.com/film2'],
    reviewed: false,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p2',
    name: 'Marcus Thompson',
    position: 'WR',
    positionGroup: 'Offense',
    size: '6\'1" 195 lbs',
    eligibility: 'Junior',
    origin: 'USC',
    pool: 'Transfer',
    fitScore: 91,
    readinessScore: 92,
    riskScore: 8,
    reasons: ['Elite route running', 'Reliable hands', 'YAC ability', 'Immediate starter'],
    flags: [],
    filmLinks: ['https://example.com/film3'],
    reviewed: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p3',
    name: 'DeShawn Williams',
    position: 'EDGE',
    positionGroup: 'Defense',
    size: '6\'4" 255 lbs',
    eligibility: 'RS Sophomore',
    origin: 'Georgia',
    pool: 'Transfer',
    fitScore: 89,
    readinessScore: 85,
    riskScore: 15,
    reasons: ['Elite pass rush', 'SEC experience', 'Motor and effort'],
    flags: ['Limited snaps last season', 'Scheme fit question'],
    filmLinks: ['https://example.com/film4'],
    reviewed: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p4',
    name: 'Chris Anderson',
    position: 'CB',
    positionGroup: 'Defense',
    size: '6\'0" 185 lbs',
    eligibility: 'Senior',
    origin: 'Alabama',
    pool: 'Transfer',
    fitScore: 87,
    readinessScore: 95,
    riskScore: 5,
    reasons: ['NFL draft prospect', 'Elite coverage skills', 'Ball hawk'],
    flags: [],
    filmLinks: ['https://example.com/film5', 'https://example.com/film6'],
    reviewed: true,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p5',
    name: 'Jordan Mitchell',
    position: 'RB',
    positionGroup: 'Offense',
    size: '5\'11" 210 lbs',
    eligibility: 'Junior',
    origin: 'Texas A&M',
    pool: 'Transfer',
    fitScore: 85,
    readinessScore: 90,
    riskScore: 10,
    reasons: ['Three-down back', 'Pass protection skills', 'Durable'],
    flags: ['Crowded backfield at origin'],
    filmLinks: ['https://example.com/film7'],
    reviewed: false,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p6',
    name: 'Tre Jackson',
    position: 'S',
    positionGroup: 'Defense',
    size: '6\'2" 205 lbs',
    eligibility: 'RS Junior',
    origin: 'Michigan',
    pool: 'Transfer',
    fitScore: 83,
    readinessScore: 82,
    riskScore: 18,
    reasons: ['Versatile defender', 'Big hitter', 'Leadership'],
    flags: ['Minor injury history', 'Adjustment to new scheme'],
    filmLinks: ['https://example.com/film8'],
    reviewed: false,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p7',
    name: 'Anthony Davis',
    position: 'OT',
    positionGroup: 'Offense',
    size: '6\'6" 315 lbs',
    eligibility: 'RS Sophomore',
    origin: 'Notre Dame',
    pool: 'Transfer',
    fitScore: 81,
    readinessScore: 78,
    riskScore: 20,
    reasons: ['Elite size', 'Good feet', 'High ceiling'],
    flags: ['Needs development', 'Pass pro inconsistent'],
    filmLinks: ['https://example.com/film9'],
    reviewed: false,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p8',
    name: 'Kevin Brown',
    position: 'LB',
    positionGroup: 'Defense',
    size: '6\'2" 235 lbs',
    eligibility: 'Junior',
    origin: 'Clemson',
    pool: 'Transfer',
    fitScore: 79,
    readinessScore: 85,
    riskScore: 14,
    reasons: ['Tackling machine', 'Run stopper', 'Experienced'],
    flags: ['Coverage limitations'],
    filmLinks: ['https://example.com/film10'],
    reviewed: true,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_EVENTS: Event[] = [
  {
    id: 'e1',
    type: 'portal_entry',
    playerId: 'p1',
    playerName: 'Jaylen Carter',
    description: 'Jaylen Carter entered the transfer portal',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'e2',
    type: 'portal_entry',
    playerId: 'p3',
    playerName: 'DeShawn Williams',
    description: 'DeShawn Williams entered the transfer portal',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'e3',
    type: 'player_reviewed',
    playerId: 'p2',
    playerName: 'Marcus Thompson',
    description: 'Marcus Thompson marked as reviewed',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    userId: 'u1',
  },
];

export const SEED_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Review Jaylen Carter film',
    description: 'Watch all available film and provide evaluation notes',
    assignedTo: 'u4',
    assignedBy: 'u1',
    playerId: 'p1',
    playerName: 'Jaylen Carter',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 't2',
    title: 'Compliance check on Marcus Thompson',
    description: 'Verify eligibility and transfer status',
    assignedTo: 'u5',
    assignedBy: 'u2',
    playerId: 'p2',
    playerName: 'Marcus Thompson',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'in_progress',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const ADDITIONAL_PLAYER_NAMES = [
  'Brandon Lewis',
  'Malik Robinson',
  'Isaiah Young',
  'Xavier Martinez',
  'Devon Harris',
  'Cameron White',
];

export const POSITIONS = ['QB', 'RB', 'WR', 'TE', 'OT', 'OG', 'C', 'EDGE', 'DT', 'LB', 'CB', 'S'];
export const ORIGINS = ['Alabama', 'Georgia', 'Ohio State', 'Michigan', 'USC', 'Texas', 'Clemson', 'Oregon', 'Penn State', 'LSU'];
