import { Player, DemoEvent, Task, DemoUser, FeatureFlags, ProgramDNA } from '@/types';

export const DEFAULT_FLAGS: FeatureFlags = {
  base_platform: true,
  daily_brief: true,
  portal_live: true,
  players_module: true,
  player_profile: true,
  tasks_module: true,
  program_dna: true,
  audit_logging: true,
  compliance_guardrails: true,
  coach_agent: true,
  memory_engine: false,
  alerts_realtime: false,
  sms_daily: false,
  coach_network_pro: false,
  enterprise_institutional: false,
  api_licensing: false,
  film_ai: false,
  nil_engine: false,
  roster_module: true,
  fit_lab: true,
};

export const DEMO_USERS: DemoUser[] = [
  { id: "u1", name: "Coach (HC)", role: "HC" },
  { id: "u2", name: "Recruiting Coordinator", role: "GM_RC" },
  { id: "u3", name: "Offensive Coordinator", role: "COORDINATOR" },
  { id: "u4", name: "Defensive Coordinator", role: "COORDINATOR" },
  { id: "u5", name: "Analyst/GA", role: "ANALYST_GA" },
];

export const DEMO_PROGRAM_DNA: ProgramDNA = {
  program: "UNLV Football (Demo)",
  recruitingPriorities: [
    "Portal speed: identify impact starters first",
    "Culture + locker room fit",
    "Immediate OL/DL depth",
    "Special teams value for roster spots",
  ],
  schemeNotes: {
    offense: "Tempo concepts + wide protections (demo assumptions)",
    defense: "Multiple front pressure packages (demo assumptions)",
  },
  fitRules: [
    "Prefer fitScore >= 85 for travel/priority",
    "Auto-flag prior transfers as risk MED",
    "Boost OL and EDGE priority in this demo build",
  ],
};

export const SEED_PLAYERS: Player[] = [
  {
    id: "p1",
    name: "Malik Neighbors",
    position: "OT",
    positionGroup: "OL",
    height: "6'6\"",
    weight: "315",
    classYear: "JR",
    eligibility: "2 years",
    pool: "TRANSFER_PORTAL",
    originSchool: "Midwest State (FBS)",
    hometown: "Dallas",
    state: "TX",
    enteredAt: "2025-12-15T22:10:00Z",
    status: "NEW",
    fitScore: 94,
    readiness: "HIGH",
    risk: "LOW",
    reasons: [
      "Scheme fit: pass-pro sets align with UNLV tempo & split-zone packages",
      "Immediate need: tackles depth + veteran starts",
      "Athletic profile: length + lateral quickness supports wide protections",
    ],
    flags: ["Medical: Clean", "Academics: OK", "Eligibility verified (demo)"],
    filmLinks: [
      { label: "2025 Cutups (placeholder)", url: "#" },
      { label: "Pass Pro Snaps (placeholder)", url: "#" },
    ],
    nilRange: { low: 150000, mid: 225000, high: 350000, rationale: "P5 starter level tackle, high demand" },
    reviewed: false,
  },
  {
    id: "p2",
    name: "Jalen Cross",
    position: "EDGE",
    positionGroup: "DL",
    height: "6'4\"",
    weight: "255",
    classYear: "SR",
    eligibility: "1 year",
    pool: "TRANSFER_PORTAL",
    originSchool: "Coastal Tech (FBS)",
    hometown: "Phoenix",
    state: "AZ",
    enteredAt: "2025-12-15T20:40:00Z",
    status: "UPDATED",
    fitScore: 91,
    readiness: "HIGH",
    risk: "MED",
    reasons: [
      "Explosive first step: fits UNLV pressure packages",
      "Production trend up last 6 games",
      "Can play EDGE or 5-tech in multiple fronts",
    ],
    flags: ["Risk: Prior transfer", "NIL expectations unknown (demo)"],
    filmLinks: [{ label: "Sacks/Pressures Reel (placeholder)", url: "#" }],
    nilRange: { low: 100000, mid: 175000, high: 250000, rationale: "Productive pass rusher, 1 yr remaining" },
    reviewed: false,
  },
  {
    id: "p3",
    name: "Trey Holloway",
    position: "WR",
    positionGroup: "WR",
    height: "6'1\"",
    weight: "195",
    classYear: "SO",
    eligibility: "3 years",
    pool: "JUCO",
    originSchool: "South Desert JC",
    hometown: "Las Vegas",
    state: "NV",
    enteredAt: "2025-12-14T18:20:00Z",
    status: "NEW",
    fitScore: 88,
    readiness: "MED",
    risk: "LOW",
    reasons: [
      "Local pipeline + immediate depth",
      "YAC ability: fits space concepts",
      "Strong special teams upside",
    ],
    flags: ["Needs: route tree refinement (demo)"],
    filmLinks: [{ label: "JUCO Highlights (placeholder)", url: "#" }],
    nilRange: { low: 25000, mid: 50000, high: 75000, rationale: "JUCO prospect, development upside" },
    reviewed: true,
  },
  {
    id: "p4",
    name: "DeAndre Vale",
    position: "CB",
    positionGroup: "DB",
    height: "6'0\"",
    weight: "185",
    classYear: "GR",
    eligibility: "1 year",
    pool: "TRANSFER_PORTAL",
    originSchool: "Atlantic U (FBS)",
    hometown: "Tampa",
    state: "FL",
    enteredAt: "2025-12-15T17:05:00Z",
    status: "WITHDRAWN",
    fitScore: 86,
    readiness: "HIGH",
    risk: "MED",
    reasons: ["Man coverage fit", "Veteran leadership", "Ball production"],
    flags: ["Status: Withdrawn (demo)"],
    filmLinks: [{ label: "Coverage Clips (placeholder)", url: "#" }],
    nilRange: { low: 80000, mid: 120000, high: 180000, rationale: "Experience cornerback, market rate" },
    reviewed: true,
  },
  {
    id: "p5",
    name: "Caleb Winters",
    position: "QB",
    positionGroup: "QB",
    height: "6'3\"",
    weight: "215",
    classYear: "JR",
    eligibility: "2 years",
    pool: "TRANSFER_PORTAL",
    originSchool: "Northern Plains (FCS)",
    hometown: "Boise",
    state: "ID",
    enteredAt: "2025-12-15T19:30:00Z",
    status: "NEW",
    fitScore: 84,
    readiness: "MED",
    risk: "MED",
    reasons: [
      "Accuracy profile fits quick-game concepts",
      "Experience in tempo offenses",
      "Upside with QB development staff",
    ],
    flags: ["Step-up competition (demo)"],
    filmLinks: [{ label: "All Throws (placeholder)", url: "#" }],
    nilRange: { low: 75000, mid: 125000, high: 200000, rationale: "FCS transfer QB, development path" },
    reviewed: false,
  },
];

export const SEED_EVENTS: DemoEvent[] = [
  {
    id: "e1",
    ts: "2025-12-16T11:55:00Z",
    type: "PORTAL_NEW",
    playerId: "p1",
    message: "New portal entry: Malik Neighbors (OT) matched UNLV OL needs.",
  },
  {
    id: "e2",
    ts: "2025-12-16T11:50:00Z",
    type: "PORTAL_UPDATED",
    playerId: "p2",
    message: "Update: Jalen Cross (EDGE) profile updated — fit score increased.",
  },
  {
    id: "e3",
    ts: "2025-12-16T11:40:00Z",
    type: "PORTAL_WITHDRAWN",
    playerId: "p4",
    message: "Withdrawn: DeAndre Vale (CB) removed from active board.",
  },
];

export const SEED_TASKS: Task[] = [
  {
    id: "t1",
    ts: "2025-12-16T12:00:00Z",
    title: "OC: Quick eval on Malik Neighbors (OT) + grade pass-pro sets",
    owner: "Offensive Coordinator",
    status: "OPEN",
    due: "2025-12-16T18:00:00Z",
    playerId: "p1",
  },
  {
    id: "t2",
    ts: "2025-12-16T12:02:00Z",
    title: "DC: Verify EDGE fit on Jalen Cross + flag any risk concerns",
    owner: "Defensive Coordinator",
    status: "OPEN",
    due: "2025-12-16T18:00:00Z",
    playerId: "p2",
  },
];

export const ADDITIONAL_PLAYER_NAMES = [
  'Marcus Reed',
  'Jordan Banks',
  'Tyrell Washington',
  'Cameron Hughes',
  'Devonte Mills',
  'Isaiah Porter',
];

export const POSITIONS = ['QB', 'RB', 'WR', 'TE', 'OT', 'OG', 'C', 'EDGE', 'DT', 'LB', 'CB', 'S'];
export const ORIGINS = ['Oklahoma State', 'Arizona', 'Colorado', 'Utah', 'San Diego State', 'Fresno State', 'Boise State', 'Oregon State', 'Washington State', 'Cal'];
