import type { FilmAsset, Play, FilmAnalytics, PlayerDevelopment, GeneratedReport } from '@/types/film';

export const SEED_FILM_ASSETS: FilmAsset[] = [
  {
    id: 'film1',
    title: 'Week 8 vs Arizona',
    type: 'GAME',
    opponent: 'Arizona Wildcats',
    date: '2024-10-19',
    angles: ['ENDZONE', 'SIDELINE', 'ALL22'],
    status: 'PROCESSED',
    confidence: 94,
    playsDetected: 67,
  },
  {
    id: 'film2',
    title: 'Week 7 vs Oregon State',
    type: 'GAME',
    opponent: 'Oregon State Beavers',
    date: '2024-10-12',
    angles: ['ENDZONE', 'SIDELINE'],
    status: 'PROCESSED',
    confidence: 91,
    playsDetected: 72,
  },
  {
    id: 'film3',
    title: 'Tuesday Practice 10/22',
    type: 'PRACTICE',
    opponent: '',
    date: '2024-10-22',
    angles: ['ENDZONE'],
    status: 'PROCESSING',
    confidence: 0,
    playsDetected: 0,
  },
  {
    id: 'film4',
    title: 'Week 6 vs Fresno State',
    type: 'GAME',
    opponent: 'Fresno State Bulldogs',
    date: '2024-10-05',
    angles: ['ENDZONE', 'SIDELINE', 'ALL22'],
    status: 'PROCESSED',
    confidence: 96,
    playsDetected: 64,
  },
];

export const SEED_PLAYS: Play[] = [
  {
    playId: 'play1',
    filmId: 'film1',
    quarter: 1,
    clock: '12:34',
    down: 1,
    distance: 10,
    yardline: 25,
    aiPlayType: 'RUN',
    aiConcept: 'Inside Zone',
    defShell: 'Nickel 4-2-5',
    confidence: 92,
    tags: ['MOTION_JET', 'PERSONNEL_11', 'HASH_LEFT'],
    aiNotes: 'Strong side run with pulling guard. LB slow to fill A-gap.',
    recommendedActions: ['Review guard technique', 'Add to cutup: Inside Zone success'],
    poster: '/placeholder.svg',
    trackingSummary: {
      avgSpeed: 14.2,
      maxSpeed: 19.8,
      totalDistance: 42,
      topPlayer: 'RB #22 - 4.51s 40 equivalent burst',
    },
    assignmentInference: {
      bustDetected: false,
      assignments: [
        { player: 'C #55', task: 'Reach block', grade: 'A' },
        { player: 'LG #72', task: 'Pull & kick', grade: 'B+' },
      ],
    },
  },
  {
    playId: 'play2',
    filmId: 'film1',
    quarter: 1,
    clock: '11:02',
    down: 2,
    distance: 6,
    yardline: 31,
    aiPlayType: 'PASS',
    aiConcept: 'Mesh Concept',
    defShell: 'Cover 3',
    confidence: 88,
    tags: ['PERSONNEL_11', 'HASH_RIGHT', 'RPO_TAG'],
    aiNotes: 'Mesh with RPO tag. LB bit on fake, opened window over middle.',
    recommendedActions: ['Highlight for QB film study', 'Tag: Red Zone ready'],
    poster: '/placeholder.svg',
    trackingSummary: {
      avgSpeed: 11.3,
      maxSpeed: 17.2,
      totalDistance: 38,
      topPlayer: 'WR #8 - Clean release, 4.8s route',
    },
    assignmentInference: {
      bustDetected: false,
      assignments: [
        { player: 'WR #8', task: 'Over route', grade: 'A' },
        { player: 'TE #87', task: 'Under route', grade: 'A-' },
      ],
    },
  },
  {
    playId: 'play3',
    filmId: 'film1',
    quarter: 2,
    clock: '08:45',
    down: 3,
    distance: 7,
    yardline: 42,
    aiPlayType: 'PASS',
    aiConcept: 'Four Verticals',
    defShell: 'Cover 1 Robber',
    confidence: 85,
    tags: ['PERSONNEL_10', 'EMPTY', 'PRESSURE_5'],
    aiNotes: 'Empty set vs 5-man pressure. Safety robbed post, incomplete.',
    recommendedActions: ['ID pre-snap tell', 'Add to 3rd down failures cutup'],
    poster: '/placeholder.svg',
    trackingSummary: {
      avgSpeed: 16.1,
      maxSpeed: 21.4,
      totalDistance: 54,
      topPlayer: 'WR #1 - Deep post route, contested',
    },
    assignmentInference: {
      bustDetected: true,
      bustReason: 'Hot route not activated vs pressure',
      assignments: [
        { player: 'QB #7', task: 'Hot read', grade: 'C' },
        { player: 'RB #22', task: 'Blitz pickup', grade: 'B' },
      ],
    },
  },
  {
    playId: 'play4',
    filmId: 'film1',
    quarter: 3,
    clock: '14:22',
    down: 1,
    distance: 10,
    yardline: 20,
    aiPlayType: 'RUN',
    aiConcept: 'Power',
    defShell: 'Base 4-3',
    confidence: 94,
    tags: ['PERSONNEL_12', 'HASH_MIDDLE', 'RED_ZONE'],
    aiNotes: 'Power run with lead TE. Hole opened clean, 8-yard gain.',
    recommendedActions: ['Highlight blocking execution', 'Add to Red Zone success cutup'],
    poster: '/placeholder.svg',
    trackingSummary: {
      avgSpeed: 13.8,
      maxSpeed: 18.5,
      totalDistance: 36,
      topPlayer: 'FB #45 - Elite lead block',
    },
    assignmentInference: {
      bustDetected: false,
      assignments: [
        { player: 'RG #68', task: 'Pull & lead', grade: 'A+' },
        { player: 'TE #87', task: 'Kick out', grade: 'A' },
      ],
    },
  },
];

export const SEED_FILM_ANALYTICS: FilmAnalytics = {
  runPass: { run: 45, pass: 55 },
  conceptFreq: [
    { concept: 'Inside Zone', count: 18 },
    { concept: 'RPO Mesh', count: 14 },
    { concept: 'Power', count: 12 },
    { concept: 'Mesh Concept', count: 10 },
    { concept: 'Four Verticals', count: 8 },
    { concept: 'Outside Zone', count: 7 },
  ],
  runDirectionHeat: {
    left: 35,
    middle: 40,
    right: 25,
  },
  targetZoneHeat: {
    short_left: 20,
    short_middle: 25,
    short_right: 18,
    deep_left: 12,
    deep_middle: 15,
    deep_right: 10,
  },
  defShells: [
    { shell: 'Cover 3', count: 22 },
    { shell: 'Nickel 4-2-5', count: 18 },
    { shell: 'Cover 1', count: 14 },
    { shell: 'Base 4-3', count: 10 },
    { shell: 'Cover 2', count: 8 },
  ],
};

export const SEED_PLAYER_DEVELOPMENT: PlayerDevelopment[] = [
  {
    playerId: 'dev1',
    name: 'Marcus Johnson',
    position: 'WR',
    weeklyTrend: 'UP',
    issues: ['Route stem inconsistency', 'Contested catch rate'],
    drills: ['Stem drill ladder', 'High-point ball work'],
    progressScore: 72,
  },
  {
    playerId: 'dev2',
    name: 'Tyler Williams',
    position: 'OT',
    weeklyTrend: 'FLAT',
    issues: ['Pass set depth', 'Hand placement vs speed'],
    drills: ['Kick-slide reps', 'Mirror drill'],
    progressScore: 65,
  },
  {
    playerId: 'dev3',
    name: 'Jordan Smith',
    position: 'LB',
    weeklyTrend: 'UP',
    issues: ['Zone drop depth', 'Pursuit angle'],
    drills: ['Drop depth reads', 'Angle pursuit circuit'],
    progressScore: 78,
  },
];

export const SEED_GENERATED_REPORT: GeneratedReport = {
  title: 'Scout Report: Arizona Wildcats',
  generatedAt: new Date().toISOString(),
  sections: [
    {
      heading: '1ST DOWN TENDENCIES',
      bullets: [
        'Run/Pass: 58% Run / 42% Pass (n=24)',
        'Primary formation: 11 Personnel (67%)',
        'Key concepts: Inside Zone (42%), RPO (28%)',
        'Play-action: 18% of 1st down passes',
      ],
    },
    {
      heading: '3RD DOWN TENDENCIES',
      bullets: [
        'Short (1-3): 78% conversion, mostly QB runs',
        'Medium (4-6): 52% conversion, mesh concepts dominate',
        'Long (7+): 31% conversion, four verts heavy',
        'Hot route usage on pressure: 65%',
      ],
    },
    {
      heading: 'RED ZONE',
      bullets: [
        'TD rate: 72% (13/18 trips)',
        'Heavy 12 personnel inside the 10',
        'Power/Counter: 60% of goal line runs',
        'Fade routes: 80% to boundary WR',
      ],
    },
    {
      heading: 'KEY TAKEAWAYS',
      bullets: [
        'Predictable: Inside Zone on 1st & 10 from own territory',
        'Exploit: LBs slow to mesh exchanges — run RPO killers',
        'Watch: #7 QB scramble tendency when 1st read covered',
      ],
    },
  ],
};

export const OPPONENT_OPTIONS = [
  'Arizona Wildcats',
  'Oregon State Beavers',
  'Fresno State Bulldogs',
  'San Diego State Aztecs',
  'Boise State Broncos',
];
