import { FeatureFlags } from '@/types';

export const DEFAULT_FLAGS: FeatureFlags = {
  base_platform: true,
  daily_brief: true,
  portal_live: true,
  players_module: true,
  player_profile: true,
  tasks_module: true,
  program_dna: true,
  audit_logging: true,
  compliance_guardrails: true,
  coach_agent: true,
  memory_engine: false,
  alerts_realtime: false,
  sms_daily: false,
  coach_network_pro: true,
  enterprise_institutional: false,
  api_licensing: false,
  film_ai: false,
  nil_engine: false,
  roster_module: true,
  fit_lab: true,
  budget_core: true,
  budget_simulator: false,
  budget_forecast: false,
  risk_heatmaps: false,
};
