-- Disable RLS on all football tables for demo mode
ALTER TABLE programs DISABLE ROW LEVEL SECURITY;
ALTER TABLE seasons DISABLE ROW LEVEL SECURITY;
ALTER TABLE fb_players DISABLE ROW LEVEL SECURITY;
ALTER TABLE fb_revshare_pools DISABLE ROW LEVEL SECURITY;
ALTER TABLE fb_revshare_policies DISABLE ROW LEVEL SECURITY;
ALTER TABLE fb_player_season_usage DISABLE ROW LEVEL SECURITY;
ALTER TABLE fb_player_grades DISABLE ROW LEVEL SECURITY;
ALTER TABLE fb_player_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE fb_value_snapshots DISABLE ROW LEVEL SECURITY;

-- Also disable on existing film tables for consistency
ALTER TABLE film_assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE play_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE playbook_concepts DISABLE ROW LEVEL SECURITY;
ALTER TABLE player_development DISABLE ROW LEVEL SECURITY;
ALTER TABLE player_tracks DISABLE ROW LEVEL SECURITY;
ALTER TABLE plays DISABLE ROW LEVEL SECURITY;